guest = ['prince', 'elvis', 'tesla']
name = guest[0].title()
print(name + ", can you come to my BBQ?")
name = guest[1].title()
print(name + ", can you come to my BBQ?")
name = guest[2].title()
print(name + ", can you come to my BBQ?")
name = guest[0].title()
print("\nSorry, " + name + " can't make it to the BBQ.")
del(guest[0])
guest.insert(0, 'stonecold')
name = guest[0].title()
print(name + ", can you come to my BBQ?")
name = guest[1].title()
print(name + ", can you come to my BBQ?")
name = guest[2].title()
print(name + ", can you come to my BBQ?")
print("\nWe have got a bigger table!")
guest.insert(0, 'shaft')
guest.insert(2, 'sting')
guest.append('mankind')
name = guest[0].title()
print(name + ", can you come to my BBQ?")
name = guest[1].title()
print(name + ", can you come to my BBQ?")
name = guest[2].title()
print(name + ", can you come to my BBQ?")
name = guest[3].title()
print(name + ", can you come to my BBQ?")
name = guest[4].title()
print(name + ", can you come to my BBQ?")
name = guest[5].title()
print(name + ", can you come to my BBQ?")
print("\nSorry, we can only two spots left at the BBQ.")
name = guest.pop()
print("Sorry, " + name.title() + " there's no room at the BBQ.")
name = guest.pop()
print("Sorry, " + name.title() + " there's no room at the BBQ.")
name = guest.pop()
print("Sorry, " + name.title() + " there's no room at the BBQ.")
name = guest.pop()
print("Sorry, " + name.title() + " there's no room at the BBQ.")
name = guest[0].title()
print(name + ", can you come to my BBQ?")
name = guest[1].title()
print(name + ", can you come to my BBQ?")
del(guest[0])
del(guest[0])
print(guest)


